// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx7rnPv3MC8Bt__voYfphotuxtuAfreX4',
    appId: '1:776574456095:web:53ff79799d1de39833a02a',
    messagingSenderId: '776574456095',
    projectId: 'eduplanclassroomapp',
    authDomain: 'eduplanclassroomapp.firebaseapp.com',
    storageBucket: 'eduplanclassroomapp.firebasestorage.app',
    measurementId: 'G-2TJ895G40F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMQFf8F4I5zqhiuhC3mstfCqXpA2CiAIg',
    appId: '1:776574456095:android:34fcf9674f39891333a02a',
    messagingSenderId: '776574456095',
    projectId: 'eduplanclassroomapp',
    storageBucket: 'eduplanclassroomapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo7DKSF6pvrUA-XgIuRQWgVzJK8yl2qV4',
    appId: '1:776574456095:ios:cca273da56e5a8fd33a02a',
    messagingSenderId: '776574456095',
    projectId: 'eduplanclassroomapp',
    storageBucket: 'eduplanclassroomapp.firebasestorage.app',
    iosBundleId: 'com.example.eduplan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo7DKSF6pvrUA-XgIuRQWgVzJK8yl2qV4',
    appId: '1:776574456095:ios:cca273da56e5a8fd33a02a',
    messagingSenderId: '776574456095',
    projectId: 'eduplanclassroomapp',
    storageBucket: 'eduplanclassroomapp.firebasestorage.app',
    iosBundleId: 'com.example.eduplan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx7rnPv3MC8Bt__voYfphotuxtuAfreX4',
    appId: '1:776574456095:web:8b12985ef511280133a02a',
    messagingSenderId: '776574456095',
    projectId: 'eduplanclassroomapp',
    authDomain: 'eduplanclassroomapp.firebaseapp.com',
    storageBucket: 'eduplanclassroomapp.firebasestorage.app',
    measurementId: 'G-HHBQS9T2RJ',
  );

}